/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelModelIdRouteImport } from './routes/model/$modelId'
import { Route as ApiSummaryModeRouteImport } from './routes/api/summary.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelModelIdRoute = ModelModelIdRouteImport.update({
  id: '/model/$modelId',
  path: '/model/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryModeRoute = ApiSummaryModeRouteImport.update({
  id: '/api/summary/$mode',
  path: '/api/summary/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/api/summary/$mode': typeof ApiSummaryModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/api/summary/$mode': typeof ApiSummaryModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/api/summary/$mode': typeof ApiSummaryModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/model/$modelId' | '/api/summary/$mode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/model/$modelId' | '/api/summary/$mode'
  id: '__root__' | '/' | '/model/$modelId' | '/api/summary/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelModelIdRoute: typeof ModelModelIdRoute
  ApiSummaryModeRoute: typeof ApiSummaryModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$modelId': {
      id: '/model/$modelId'
      path: '/model/$modelId'
      fullPath: '/model/$modelId'
      preLoaderRoute: typeof ModelModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/$mode': {
      id: '/api/summary/$mode'
      path: '/api/summary/$mode'
      fullPath: '/api/summary/$mode'
      preLoaderRoute: typeof ApiSummaryModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelModelIdRoute: ModelModelIdRoute,
  ApiSummaryModeRoute: ApiSummaryModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
